-- MySQL Script generated by MySQL Workbench
-- Sat Jul 10 14:30:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database SitePhoto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Database SitePhoto
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `SitePhoto` DEFAULT CHARACTER SET utf8 ;
USE `SitePhoto` ;

-- -----------------------------------------------------
-- Table `SitePhoto`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SitePhoto`.`Roles` (
  `idRoles` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NomRole` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`),
  UNIQUE INDEX `idRoles_UNIQUE` (`idRoles` ASC) ,
  UNIQUE INDEX `NomRole_UNIQUE` (`NomRole` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SitePhoto`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SitePhoto`.`Users` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Roles_idRoles` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) ,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) ,
  INDEX `fk_Users_Roles_idx` (`Roles_idRoles` ASC) ,
  CONSTRAINT `fk_Users_Roles`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `SitePhoto`.`Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `roles`(`NomRole`) VALUES ('admin'), ('visiteur');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
